<?php

/**
 * Iconocoders_Remarketing
 *
 * @category  Iconocoders
 * @package   Iconocoders_Remarketing
 * @author    Daniel Akos Kovacs, Attila Kiss, Peter Szabo
 * @copyright 2017 Iconocoders (https://iconocoders.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

$helper = Mage::helper("iconocoders_remarketing");
if (!$helper->isPixelEnabled() || !$helper->isConversionEnabled()) {
    return;
}

$quote = Mage::getSingleton('checkout/cart')->getQuote();
$pixelId = $helper->getPixelId();
$productIds = $helper->getCartProductIds($quote);
?>

<!-- Facebook Pixel Code -->
<script>
    fbq('track', 'InitiateCheckout', {
        content_name: 'Initiate Checkout',
        content_ids: '<?php echo $productIds ?>',
        content_type: 'product',
        value: '<?php echo number_format($quote->getGrandTotal(), 2, '.', '')?>',
        currency: '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>'
    });
</script>
<noscript>
    <img height="1" width="1" style="display:none"
         src="https://www.facebook.com/tr?id=<?php echo $pixelId; ?>&ev=PageView&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->
