<?php

/**
 * Iconocoders_Remarketing
 *
 * @category  Iconocoders
 * @package   Iconocoders_Remarketing
 * @author    Daniel Akos Kovacs, Attila Kiss, Peter Szabo
 * @copyright 2017 Iconocoders (https://iconocoders.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

$helper = Mage::helper("iconocoders_remarketing");
if (!$helper->isPixelEnabled() || !$helper->isConversionEnabled()) {
    return;
}
$pixelId = $helper->getPixelId();

$query = Mage::app()->getRequest()->getQuery();
?>

<!-- Facebook Pixel Code -->
<script>
fbq('track', 'Search', {
        content_category: 'product',
        search_string: '<?php echo implode(', ', $query) ?>'
    });
</script>
<noscript>
    <img height="1" width="1" style="display:none"
         src="https://www.facebook.com/tr?id=<?php echo $pixelId; ?>&ev=PageView&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->