<?php

/**
 * Iconocoders_Remarketing
 *
 * @category  Iconocoders
 * @package   Iconocoders_Remarketing
 * @author    Daniel Akos Kovacs, Attila Kiss, Peter Szabo
 * @copyright 2017 Iconocoders (https://iconocoders.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

$helper = Mage::helper("iconocoders_remarketing");
if (!$helper->isPixelEnabled()) {
    return;
}
$pixelId = $helper->getPixelId();
?>
<!-- Facebook Pixel Code -->
<script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

    fbq('init', '<?php echo $pixelId; ?>');
    fbq('track', "PageView");</script>
<noscript>
    <img height="1" width="1" style="display:none"
               src="https://www.facebook.com/tr?id=<?php echo $pixelId; ?>&ev=PageView&noscript=1"
    />
</noscript>
<!-- End Facebook Pixel Code -->
