<?php

/**
 * Iconocoders_Remarketing
 *
 * @category  Iconocoders
 * @package   Iconocoders_Remarketing
 * @author    Daniel Akos Kovacs, Attila Kiss, Peter Szabo
 * @copyright 2017 Iconocoders (https://iconocoders.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

$helper = Mage::helper("iconocoders_remarketing");
?>

<?php if($helper->isPixelEnabled()): ?>
    <script type="text/javascript">
        var google_tag_params = <?php echo $this->getJsConfigParams(); ?>;
    </script>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = <?php echo $helper->getGoogleConversionId(); ?>;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = <?php echo $helper->getGoogleRemarketingOnly(); ?>;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $helper->getGoogleConversionId(); ?>/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
<?php endif; ?>